name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Linter Test
        uses: shivammathur/setup-php@v2
        with:
                php-version: '8.1'
                tools: phpcs, phpunit
      - run: |
          make lint
